feat: manual trigger
NeverBehave/Tweet2Telegram pull request #6
Opened 2021-05-21 07:12 UTC by yihong0618

feat for #5

2021-05-22 04:12 UTC, NeverBehave requested changes
请同时更新README说明触发方式

2021-05-23 11:15 UTC, yihong0618 commented
> 请同时更新README说明触发方式

Done

2021-05-25 01:18 UTC, NeverBehave requested changes

2021-05-25 01:18 UTC, NeverBehave commented on README.md
> +- workflow_dispatch: 手动触发或 `API` 触发
```suggestion
- workflow_dispatch: 手动触发或使用 [RESTFUL API](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) 触发，可以配合 iOS 捷径在推特客户端开启/关闭时调用，节约资源
```

2021-05-25 01:18 UTC, merged

2021-05-25 01:19 UTC, yihong0618 commented on README.md
> +- workflow_dispatch: 手动触发或 `API` 触发
谢谢。