Update README.md
NeverBehave/Tweet2Telegram pull request #7
Opened 2021-05-21 07:19 UTC by yihong0618

2021-05-22 04:14 UTC, NeverBehave requested changes

2021-05-22 04:14 UTC, NeverBehave commented on README.md
> +- GIST_TOKEN 为 [GitHub token](https://github.com/settings/tokens) 需要把相应的选项勾上
```suggestion
    - `GIST_TOKEN` 为 [GitHub token](https://github.com/settings/tokens) 需要把相应的选项勾上
```

2021-05-23 11:22 UTC, yihong0618 commented
Also add some spaces in the `doc`

2021-05-25 01:14 UTC, NeverBehave approved these changes

2021-05-25 01:14 UTC, merged